apiVersion: v1
kind: Service
metadata:
  name: fetcher
  namespace: applications
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fetcher

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher
  namespace: applications
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fetcher
  template:
    metadata:
      labels:
        app: fetcher
    spec:
      containers:
      - name: fetcher
        image: diana1996/fetcher:latest
        ports:
        - containerPort: 8080
